# Generated by Django 4.1.7 on 2023-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdrinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='description',
            field=models.TextField(default='no description added here'),
        ),
        migrations.AlterField(
            model_name='soda',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
