# Generated by Django 4.1.7 on 2023-03-01 05:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import softdrinks.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdrinks', '0002_alter_soda_description_alter_soda_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='soda',
            name='Owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soda',
            name='brand',
            field=models.CharField(max_length=100, validators=[softdrinks.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='soda',
            name='description',
            field=models.TextField(default='no description added here', validators=[softdrinks.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='soda',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000, 'value is above limit')]),
        ),
        migrations.AlterField(
            model_name='soda',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, validators=[softdrinks.validators.validate_char]),
        ),
    ]
