# Generated by Django 4.1.7 on 2023-03-01 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softdrinks', '0003_soda_owner_alter_soda_brand_alter_soda_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
